import{i as v,s as w,d as C}from"./assets/main-e068f8f2.js";import{a as i,b as E}from"./assets/vendor-4563c95f.js";class p{async fetchCategories(){try{return(await i.get("https://books-backend.p.goit.global/books/category-list")).data}catch(o){throw console.error("Error fetching categories:",o),o}}async fetchTopCategories(){try{return(await i.get("https://books-backend.p.goit.global/books/top-books")).data}catch(o){throw console.error("Error fetching top categories:",o),o}}async fetchBooksByCategory(o){try{return(await i.get(`https://books-backend.p.goit.global/books/category?category=${o}`)).data}catch(t){throw console.error("Error fetching books by category:",t),t}}async fetchBookById(o){try{return(await i.get(`https://books-backend.p.goit.global/books/${o}`)).data}catch(t){throw console.error("Error fetching book by ID:",t),t}}}const k=document.querySelector(".category-list"),d=document.querySelector(".gallery-list"),b=document.querySelector("#all-categories"),u=document.querySelector(".category-title"),y=new p;async function q(){try{const e=await y.fetchCategories();B(e),b.classList.add("active")}catch(e){console.log("Failed to render show category list:",e)}}q();async function m(){document.querySelectorAll(".category-list-item").forEach(e=>e.classList.remove("active"));try{const e=await y.fetchTopCategories();for(let t=0;t<4;t++)T(e[t]);document.querySelector(".category-list-item").classList.add("active")}catch(e){console.error("Failed to fetch all categories:",e)}document.querySelectorAll(".see-more-btn").forEach(e=>e.addEventListener("click",f))}m();function B(e){const o=e.map(({list_name:t})=>`
        <li class="category-list-item">
            <h4 class="category-name">${t}</h4>
        </li>`).join("");k.innerHTML+=o}function L(e){return e.map(({_id:t,book_image:c,author:n,title:s})=>`
        <li class="gallery-item" id="${t}">
            <img src="${c}" alt="" class="book-cover" />
            <h3 class="book-title">${h(s)}</h3>
            <h5 class="book-author">${h(n)}</h5>
        </li>`).join("")}function T(e){S("Best Sellers Books");const{list_name:t,books:c}=e,n=`
    <li class="gallery-list-group">
      <h3 class="list-group-name">${t}</h3>
        <ul class="gallery-list-item">
          ${L(c)}
        </ul>
      <button class="see-more-btn">See more</button>
    </li>`;d.innerHTML+=n}function x(e){const o=e[0].list_name;S(o);const t=L(e);d.innerHTML=t}async function f(e){const o=e.target.closest("li").children[0].textContent;try{const t=await y.fetchBooksByCategory(o);d.innerHTML="",t.length!=0?(d.style.cssText="flex-direction: row; flex-wrap: wrap",x(t),document.querySelectorAll(".category-list-item").forEach(c=>c.classList.remove("active"))):m(),e.target.closest("li").classList.add("active")}catch(t){console.error("Failed to render page by category:",t)}}function h(e){return e.length>=15?`${e.slice(0,15)}...`:e}function S(e){let o=e.split(" ");const t=o[o.length-1];o=o.slice(0,o.length-1);const c=o.join(" ");u.textContent=`${c}`,u.nextElementSibling.textContent=`${t}`}k.addEventListener("click",f);b.addEventListener("click",m);const $=new p;document.querySelector(".gallery-list").addEventListener("click",async e=>{const o=e.target.parentNode.getAttribute("id"),t=await $.fetchBookById(o);A(t)});const A=e=>{let o,t;const c=document.querySelector("#modal-template"),n=new E.create(c,{onShow:r=>{document.body.classList.add("modal-opened"),o=g=>{g.key==="Escape"&&r.close()},document.addEventListener("keydown",o),t=g=>{r.close()},r.element().querySelector(".modal-close").addEventListener("click",t)},onClose:r=>{document.removeEventListener("keydown",o),r.element().querySelector(".modal-close").removeEventListener("click",t),document.body.classList.remove("modal-opened")}}),s=n.element();s.querySelector(".book-img").src=e.book_image,s.querySelector(".book-name").innerText=e.title,s.querySelector(".book-author").innerText=e.author,s.querySelector(".book-description").innerText=e.description,s.querySelector(".book-description").innerText=e.description,e.buy_links.forEach(r=>{r.name==="Amazon"?s.querySelector(".book-links-amazon").href=r.url:r.name==="Apple Books"&&(s.querySelector(".book-links-applebook").href=r.url)});const l=s.querySelector(".addToList"),a=s.querySelector(".removeFromList");v(e._id)&&(l.classList.add("hidden"),a.classList.remove("hidden")),l.addEventListener("click",r=>{r.preventDefault(),w(e),s.querySelector(".removeFromList-info").classList.remove("hidden"),l.classList.add("hidden"),a.classList.remove("hidden")}),a.addEventListener("click",r=>{r.preventDefault(),C(e._id),s.querySelector(".removeFromList-info").classList.add("hidden"),l.classList.remove("hidden"),a.classList.add("hidden")}),n.show()};
//# sourceMappingURL=commonHelpers.js.map
