import{a}from"./assets/vendor-253144a7.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();document.getElementById("burger-menu");document.querySelector("#book-list");const d=document.getElementById("themeSwitch");window.addEventListener("DOMContentLoaded",function(){const s=localStorage.getItem("theme");s&&(document.body.classList.add(s),s==="dark-theme"&&(d.checked=!0))});d.addEventListener("change",function(){this.checked?(document.body.classList.add("dark-theme"),document.body.classList.remove("light-theme"),localStorage.setItem("theme","dark-theme")):(document.body.classList.remove("dark-theme"),document.body.classList.add("light-theme"),localStorage.setItem("theme","light-theme"))});class m{constructor(){this.BASE_URL="https://books-backend.p.goit.global/books",this.TOP_BOOKS_ENDPOINT="/top-books",this.CATEGORY_ENDPOINT="/category?category=",this.CATEGORY_LIST_ENDPOINT="/category-list"}async getTopBooks(){try{const e=`${this.BASE_URL}${this.TOP_BOOKS_ENDPOINT}`;return(await a.get(e)).data}catch(e){throw console.error("Error fetching popular books:",e),e}}async getBooksByCategory(e){try{const o=`${this.BASE_URL}${this.CATEGORY_ENDPOINT}${e}`;return(await a.get(o)).data}catch(o){throw console.error(`Error fetching books for category '${e}':`,o),o}}async getDetails(e){try{const o=`${this.BASE_URL}/${e}`;return(await a.get(o)).data}catch(o){throw console.error(`Error fetching details for book with ID '${e}':`,o),o}}async getCategoryList(){try{const e=`${this.BASE_URL}${this.CATEGORY_LIST_ENDPOINT}`;return(await a.get(e)).data}catch(e){throw console.error("Error fetching category list:",e),e}}}const p=new m,l=document.querySelector(".top-books-list"),f=document.querySelector(".books-title-container");function u(){let s=y(window.innerWidth);p.getTopBooks().then(e=>k(e,s)).catch(e=>console.error("Error fetching top books:",e))}function y(s){return s>=1440?5:s>=768?3:1}function k(s,e){l.innerHTML="";const o=s.map(t=>{let r=`<li><h2 class="gallery-title">${t.list_name}</h2>
    <ul class="gallery-book-list" data-filter="${t.list_name}">`,c=[];for(let i=0;i<e&&i<t.books.length;i++){let g=`<li class='gallery-book-item' data-bookid="${t.books[i]._id}">
        <a class="gallery-book-link">
        <div class="preview">
          <img class="gallery-book-img js-open-modal" data-id="${t.books[i]._id}" src="${t.books[i].book_image}" alt="${t.books[i].title}">
          <div class="actions-card">
        <p class="action-text">quick view</p>
          </div>
        </div>
          <div class="content">
            <h3 class="gallery-book-name">${t.books[i].title}</h3>
            <h4 class="gallery-book-text">${t.books[i].author}</h4>
          </div>
        </a>
      </li>`;c.push(g)}const h=c.join(" ");return r+h+"</ul></li>"}).join(" ");l.innerHTML=o;const n='<h2 class="top-books-title">Best Sellers <span class="colortext">Books</span></h2>';f.innerHTML=n}window.addEventListener("resize",()=>{u()});u();
//# sourceMappingURL=commonHelpers.js.map
